### PR TITLE
Update existing icons

### PR DESCRIPTION
**Pull request by jletey**
@mtdmali I have exported all of my updates to the existing icons! It should be easier for you now to test this locally!

### CODE REVIEW

**Comment by mtdmali** [comment]
@johnletey Thanks John! I'm gonna have a look later tonight.

**Comment by mtdmali** [comment]
@johnletey  So I tried them out on my local machine, for some reason I don't think they're scaling down as well with a more natural rounded form. It looks like you lose of the legibility on your updated icons when it's really tiny. The only icon that looks improved to me is the markdown icon.

For comparison, here's your updated icons...

Screen Shot 2019-08-01 at 8 59 05 PM

...and here's the original ones...

Screen Shot 2019-08-01 at 9 01 02 PM

If you're seeing something different on your end, post some screenshots for me. I can find time to check it on the machine I use at work tomorrow.

**Comment by jletey** [comment]
@mtdmali I honestly don't see a difference between the two screenshots

**Comment by mtdmali** [comment]
@johnletey I use a pair of Dell Ultrasharp 24 inch monitors at 1080p, and on those there's a slight difference. It's not noticeable when I look on my phone, although I'm guessing that's because it's a retina display.

I'll see if I can replicate it at work today.

**Comment by jletey** [comment]
Sounds good @mtdmali! I also have a retina display, so can't tell the difference 😄

**Comment by mtdmali** [comment]
@johnletey After some consideration, I've decided that I'm going to keep the original icons as they display better on some monitors I have that aren't retina.

That said, I would absolutely love to include the Git icon you've made. If you can, please make another PR with just that icon and I'll approve and publish.

**Pull request closed without merging**
